# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9J9MQJlgXmAvzjE-oGmGhpAMO4U-d1E
"""

import re

# Dictionary to store predefined patterns and responses
response_dict = {
    r'hello|hi|hey': "Hello! How can I assist you today?",
    r'how are you': "I'm just a bot, but I'm doing fine, thank you for asking!",
    r'bye|goodbye': "Goodbye! Have a great day!",
    r'what is your name': "I am a chatbot. I don't have a specific name, but you can call me Bot!",
    r'help': "I am here to help! Ask me anything, and I'll do my best to assist.",
    r'(your|my) (name|identity)': "I am a chatbot created to help answer your questions.",
}

# Default response for unknown queries
default_response = "I'm sorry, I didn't quite understand that. Can you rephrase?"

# Function to get a response based on the user query
def get_response(user_query):
    # Iterate through the dictionary of patterns and responses
    for pattern, response in response_dict.items():
        if re.search(pattern, user_query, re.IGNORECASE):  # Ignore case while matching
            return response
    # Return the default response if no pattern matches
    return default_response

# Chatbot interaction loop
def chatbot():
    print("Chatbot: Hello! I am here to assist you. Type 'exit' to quit.")

    while True:
        user_input = input("You: ").lower()  # Get user input and convert to lowercase
        if user_input == 'exit':
            print("Chatbot: Goodbye! Have a great day!")
            break
        else:
            response = get_response(user_input)
            print(f"Chatbot: {response}")

# Run the chatbot
if __name__ == "__main__":
    chatbot()